#!/usr/bin/env bash

###################################################################
# Copyright 2013 United States Government as represented by the
# Administrator of the National Aeronautics and Space Administration.
# All Rights Reserved.
#
# Copyright 2013 Cisco Systems, Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
#####################################################################

uplink_intf=`grep uplink_intf /etc/vinci.ini | grep -v ^# | awk -F'=' '{print $2}'`
echo CREATE OVS $uplink_intf>> /tmp/fill
ifconfig $uplink_intf up
if [ "`sudo ovs-vsctl list-br | \grep br-tun`" == "br-tun" ]; then
sudo ovs-vsctl del-br br-tun
else
echo
fi
if [ "`sudo ovs-vsctl list-br | \grep dfa_ext`" == "dfa_ext" ]; then
echo
else
sudo ovs-vsctl add-br dfa_ext
fi
if [ "`sudo ovs-vsctl list-ports br-int | \grep dfa_patch_int`" == "dfa_patch_int" ]; then
echo
else
sudo ovs-vsctl add-port br-int dfa_patch_int
sudo ovs-vsctl set interface dfa_patch_int type=patch
sudo ovs-vsctl set interface dfa_patch_int options:peer=dfa_patch_ext
fi
if [ "`sudo ovs-vsctl list-ports dfa_ext | \grep dfa_patch_ext`" == "dfa_patch_ext" ]; then
echo
else
sudo ovs-vsctl add-port dfa_ext dfa_patch_ext
sudo ovs-vsctl set interface dfa_patch_ext type=patch
sudo ovs-vsctl set interface dfa_patch_ext options:peer=dfa_patch_int
fi
if [ "`sudo ovs-vsctl list-ports dfa_ext | \grep $uplink_intf`" == "$uplink_intf" ]; then
echo
else
sudo ovs-vsctl add-port dfa_ext $uplink_intf
fi
ifconfig dfa_ext up
ifconfig dfa_ext multicast up

