#!/bin/bash

############################################
# Copyright 2013 United States Government as represented by the
# Administrator of the National Aeronautics and Space Administration.
# All Rights Reserved.
#
# Copyright 2013 Cisco Systems, Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
#################################################

sql_user=`grep mysql_user /etc/vinci.ini | grep -v ^# | awk -F'=' '{print $2}'`
sql_pass=`grep mysql_password /etc/vinci.ini | grep -v ^# | awk -F'=' '{print $2}'`
echo SQL USER PASS is $sql_user $sql_pass
sudo mysql -u$sql_user -p$sql_pass -h127.0.0.1 -e "GRANT ALL PRIVILEGES ON *.* TO '$sql_user'@'%' identified by '$sql_pass'; "
echo "SQL Ran DFA" > /tmp/sqldfaus
