#!/bin/bash

############################################
# Copyright 2013 United States Government as represented by the
# Administrator of the National Aeronautics and Space Administration.
# All Rights Reserved.
#
# Copyright 2013 Cisco Systems, Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
#################################################

# Parse vinci_location from /etc/vinci.ini
line=`cat /etc/vinci.ini | grep ^vinci\_location=`
export vinci_location=${line:15}
cd "$vinci_location"

echo hello >> ./logs/client_samp.log
vdp_vlan=$3
out=`./files/lookup.py br-int dfa_patch_int $1`
echo MAC is $1 Seg $2 VDP VLAN $3 Mode $4 Anycast $5 >> ./logs/client_samp.log
int_port=`echo $out | awk '{print $1}'`
vlan=`echo $out | awk '{print $2}'`
echo Int Port is $port VLAN is $vlan >> ./logs/client_samp.log
echo out is $out >> ./logs/client_samp.log

sudo ovs-ofctl add-flow br-int in_port=$int_port,dl_vlan=$vdp_vlan,actions=mod_vlan_vid:$vlan,normal

out=`./files/lookup.py dfa_ext dfa_patch_ext $1`
ext_port=`echo $out | awk '{print $1}'`
echo Ext Port is $ext_port >> ./logs/client_samp.log
echo out is $out >> ./logs/client_samp.log
sudo ovs-ofctl add-flow dfa_ext in_port=$ext_port,dl_vlan=$vlan,actions=mod_vlan_vid:$vdp_vlan,normal
if [ $4 -eq 1 ]
then
   sudo ovs-ofctl add-flow dfa_ext in_port=$ext_port,dl_vlan=$vlan,dl_dst=00:00:00:00:00:00/01:00:00:00:00:00,dl_type=0x0800,actions=mod_dl_dst:$5,mod_vlan_vid:$vdp_vlan,normal
fi


echo "sudo ovs-ofctl add-flow br-int in_port=$int_port,dl_vlan=$vdp_vlan,actions=mod_vlan_vid:$vlan,normal" >> ./logs/client_samp.log
echo "sudo ovs-ofctl add-flow dfa_ext in_port=$ext_port,dl_vlan=$vlan,actions=mod_vlan_vid:$vdp_vlan,normal" >> ./logs/client_samp.log
if [ $4 -eq 1 ]
then
  echo "sudo ovs-ofctl add-flow dfa_ext in_port=$ext_port,dl_vlan=$vlan,dl_dst=00:00:00:00:00:00/01:00:00:00:00:00,dl_type=0x0800,actions=mod_dl_dst:$5,mod_vlan_vid:$vdp_vlan,normal" >> ./logs/client_samp.log
fi

#sudo iptables -t filter -F
#echo "sudo iptables -t filter -F" >> /tmp/VINCI
